In [1]:
!kaggle datasets download -d muhammadshahidazeem/customer-churn-dataset

Dataset URL: https://www.kaggle.com/datasets/muhammadshahidazeem/customer-churn-dataset
License(s): GPL-2.0
customer-churn-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [2]:
import os
import zipfile

# Navigate to raw data folder
raw_path = r"C:\Users\igboa\Desktop\customer-churn-data-warehouse\data\raw"



zip_file = "customer-churn-dataset.zip"

with zipfile.ZipFile(zip_file, 'r') as z:
    z.extractall(raw_path)

print("Extracted files:", os.listdir(raw_path))

Extracted files: ['customer_churn_dataset-testing-master.csv', 'customer_churn_dataset-training-master.csv']

In [3]:
import pandas as pd
from IPython.display import display, Markdown

train_path  = r"C:\Users\igboa\Desktop\customer-churn-data-warehouse\data\raw\customer_churn_dataset-training-master.csv"
test_path = r"C:\Users\igboa\Desktop\customer-churn-data-warehouse\data\raw\customer_churn_dataset-testing-master.csv"

train_df = pd.read_csv(train_path)
test_df  = pd.read_csv(test_path)


display(Markdown("### TRAIN DATASET"))
display(train_df.head())

display(Markdown("### TEST DATASET"))
display(test_df.head())

### TRAIN DATASET

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

### TEST DATASET

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [4]:
train_df.info()
train_df.describe(include='all')
train_df.isna().sum()
train_df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

CustomerID           440832
Age                      48
Gender                    2
Tenure                   60
Usage Frequency          30
Support Calls            11
Payment Delay            31
Subscription Type         3
Contract Length           3
Total Spend           68363
Last Interaction         30
Churn                     2
dtype: int64

In [5]:
full_df = pd.concat([train_df, test_df], ignore_index=True)
full_df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [6]:
full_df.isna().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [7]:
full_df[full_df.isna().any(axis=1)]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
clean_df = full_df.dropna()

In [9]:
clean_df.isna().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [23]:
duplicate_rows = clean_df[clean_df["CustomerID"].duplicated(keep=False)]
duplicate_rows.sort_values(by="CustomerID", inplace=True)
duplicate_rows.head(10)

C:\Users\igboa\AppData\Local\Temp\ipykernel_30240\1325175704.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicate_rows.sort_values(by="CustomerID", inplace=True)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
440834,2.0,41.0,Female,28.0,28.0,7.0,13.0,Standard,Monthly,584.0,20.0,0.0
440835,3.0,47.0,Male,27.0,10.0,2.0,29.0,Premium,Annual,757.0,21.0,0.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
440836,4.0,35.0,Male,9.0,12.0,5.0,17.0,Premium,Quarterly,232.0,18.0,0.0
440837,5.0,53.0,Female,58.0,24.0,9.0,2.0,Standard,Annual,533.0,18.0,0.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0
440838,6.0,30.0,Male,41.0,14.0,10.0,10.0,Premium,Monthly,500.0,29.0,0.0

In [24]:
exact_dupes = (
    clean_df[clean_df.duplicated(keep=False)]
    .sort_values(list(clean_df.columns))
)

exact_dupes

Empty DataFrame
Columns: [CustomerID, Age, Gender, Tenure, Usage Frequency, Support Calls, Payment Delay, Subscription Type, Contract Length, Total Spend, Last Interaction, Churn]
Index: []

In [ ]:
clean_df.to_csv("../../data/processed/clean_churn.csv", index=False)

In [ ]:
from IPython.display import display, Markdown
display(Markdown("### INFO"))
clean_df.info()

display(Markdown("### NUMBER OF UNIQUE VALUES"))
clean_df.nunique()

### INFO

<class 'pandas.core.frame.DataFrame'>
Index: 505206 entries, 0 to 505206
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         505206 non-null  float64
 1   Age                505206 non-null  float64
 2   Gender             505206 non-null  object
 3   Tenure             505206 non-null  float64
 4   Usage Frequency    505206 non-null  float64
 5   Support Calls      505206 non-null  float64
 6   Payment Delay      505206 non-null  float64
 7   Subscription Type  505206 non-null  object
 8   Contract Length    505206 non-null  object
 9   Total Spend        505206 non-null  float64
 10  Last Interaction   505206 non-null  float64
 11  Churn              505206 non-null  float64
dtypes: float64(9), object(3)
memory usage: 50.1+ MB

### NUMBER OF UNIQUE VALUES

CustomerID           442211
Age                      48
Gender                    2
Tenure                   60
Usage Frequency          30
Support Calls            11
Payment Delay            31
Subscription Type         3
Contract Length           3
Total Spend           68363
Last Interaction         30
Churn                     2
dtype: int64

In [ ]:

dfSchema = pd.read_csv("../../data/processed/clean_churn.csv")

schema = pd.DataFrame({
    "column": dfSchema.columns,
    "dtype": dfSchema.dtypes.astype(str),
    "nulls": dfSchema.isna().sum(),
    "unique": dfSchema.nunique()
})

schema

                              column    dtype  nulls  unique
CustomerID                CustomerID  float64      0  442211
Age                              Age  float64      0      48
Gender                        Gender   object      0       2
Tenure                        Tenure  float64      0      60
Usage Frequency      Usage Frequency  float64      0      30
Support Calls          Support Calls  float64      0      11
Payment Delay          Payment Delay  float64      0      31
Subscription Type  Subscription Type   object      0       3
Contract Length      Contract Length   object      0       3
Total Spend              Total Spend  float64      0   68363
Last Interaction    Last Interaction  float64      0      30
Churn                          Churn  float64      0       2